// Antigravity-style editor look: one continuous dark surface shared with the agent panel (#181818),
// quiet chrome, comfortable code typography.
const SURFACE = '#181818';
const SURFACE_RAISED = '#1f1f1f';
const BORDER = '#2a2a2a';

export const EDITOR_USER_CONFIGURATION: Record<string, unknown> = {
  'workbench.colorTheme': 'Default Dark Modern',
  'workbench.tree.indent': 14,
  'workbench.tree.renderIndentGuides': 'onHover',
  'workbench.editor.tabActionLocation': 'right',
  'workbench.editor.showTabs': 'multiple',
  'workbench.list.smoothScrolling': true,
  'editor.fontFamily': "'JetBrains Mono', 'SF Mono', Menlo, Monaco, 'Courier New', monospace",
  'editor.fontSize': 13,
  'editor.lineHeight': 21,
  'editor.fontLigatures': true,
  'editor.cursorBlinking': 'smooth',
  'editor.cursorSmoothCaretAnimation': 'on',
  'editor.smoothScrolling': true,
  'editor.minimap.enabled': false,
  'editor.renderLineHighlight': 'gutter',
  'editor.bracketPairColorization.enabled': true,
  'editor.guides.bracketPairs': 'active',
  'editor.padding.top': 12,
  'editor.scrollBeyondLastLine': false,
  'editor.stickyScroll.enabled': false,
  'breadcrumbs.enabled': true,
  'workbench.colorCustomizations': {
    'editor.background': SURFACE,
    'editorGutter.background': SURFACE,
    'editor.lineHighlightBackground': '#ffffff08',
    'editor.selectionBackground': '#264f7855',
    'editorIndentGuide.background1': '#ffffff10',
    'editorIndentGuide.activeBackground1': '#ffffff30',
    'editorWidget.background': SURFACE_RAISED,
    'breadcrumb.background': SURFACE,
    'sideBar.background': SURFACE,
    'sideBar.border': BORDER,
    'sideBarSectionHeader.background': SURFACE,
    'sideBarSectionHeader.border': BORDER,
    'list.activeSelectionBackground': '#ffffff12',
    'list.inactiveSelectionBackground': '#ffffff0c',
    'list.hoverBackground': '#ffffff08',
    'activityBar.background': '#141414',
    'activityBar.border': BORDER,
    'activityBar.activeBorder': '#10b981',
    'activityBar.foreground': '#e5e7eb',
    'activityBar.inactiveForeground': '#6b7280',
    'editorGroupHeader.tabsBackground': SURFACE,
    'editorGroupHeader.tabsBorder': BORDER,
    'tab.activeBackground': SURFACE,
    'tab.inactiveBackground': '#141414',
    'tab.activeBorderTop': '#10b981',
    'tab.border': BORDER,
    'tab.activeForeground': '#f3f4f6',
    'tab.inactiveForeground': '#9ca3af',
    'panel.background': SURFACE,
    'panel.border': BORDER,
    'statusBar.background': '#141414',
    'statusBar.foreground': '#9ca3af',
    'statusBar.border': BORDER,
    'titleBar.activeBackground': '#141414',
    'scrollbarSlider.background': '#ffffff14',
    'scrollbarSlider.hoverBackground': '#ffffff24',
  },
};
